# Generated by Django 5.0.2 on 2024-06-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vague', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vague',
            name='season',
            field=models.CharField(default=2, max_length=14),
            preserve_default=False,
        ),
    ]
