# Generated by Django 5.0.2 on 2024-06-15 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vague', '0002_vague_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vague',
            old_name='quantity',
            new_name='quantity_at_the_start',
        ),
    ]
