# Generated by Django 5.0 on 2024-06-16 18:28

import datepick.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vague', '0003_rename_quantity_vague_quantity_at_the_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vague',
            name='start_date',
            field=datepick.fields.DateField(),
        ),
    ]
