# Generated by Django 5.0 on 2024-06-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('paid_off', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_male', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
    ]
